### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by KaueReinbold** [weareinlog/inlog-maps#49]
Hello guys,

Long time no see.

I would like to know if it is possible to contribute to this repository. 
I was looking for a `CONTRIBUTING.md`, but I did not find it. If it is possible to contribute to this project. 
Can you share the way you all are working?

I would love to help you and work together again on a good project.

Hope to hear from you soon.

**Comment by caroph** [comment]
Hello Kaue, 

Yes, it it possible to contribute to this repository.
I have to create a `CONTRIBUTING.md`, I will do it as soon as possible.

All contributions are welcome.
